image: Visual Studio 2017
platform: Any CPU

configuration:
- Release

before_build:
- choco install opencover.portable
- choco install codecov
- dotnet restore

build:
  project: UAUtil.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full UAUtil.Test\UAUtil.Test.csproj" -filter:"+[UAUtil*]* -[UAUtil.Test*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release

artifacts:
  - path: UAUtil\bin\Release\netstandard2.0\UAUtil.dll
    name: UAUtil.dll
  - path: UAUtil.*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: F08+ODn3ExAxMZuWu9p7b1pGQYfycvQi8RqYUgU6zWy841j3DQDgosDfaE4iyyvO