image: Visual Studio 2017
platform: Any CPU

version: 1.0.{build}

configuration:
- Release

before_build:
- choco install opencover.portable
- choco install codecov
- dotnet restore

build:
  project: UAUtil.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full UAUtil.Test\UAUtil.Test.csproj" -filter:"+[UAUtil*]* -[UAUtil.Test*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%