image: Visual Studio 2017
platform: Any CPU

version: '1.0.{build}'

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(APPVEYOR_BUILD_VERSION)'
  package_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_version: '$(APPVEYOR_BUILD_VERSION)'
  file_version: '$(APPVEYOR_BUILD_VERSION)'
  informational_version: '$(APPVEYOR_BUILD_VERSION)'

before_build:
- echo $(APPVEYOR_BUILD_VERSION)
- choco install opencover.portable
- choco install codecov
- dotnet restore

build:
  project: UAUtil.sln

test_script:
  - OpenCover.Console.exe -oldstyle -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full UAUtil.Test\UAUtil.Test.csproj" -filter:"+[UAUtil*]* -[UAUtil.Test*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%

after_test:
  - dotnet pack --configuration Release

artifacts:
  - path: UAUtil\bin\Release\netstandard2.0\UAUtil.dll
    name: UAUtil.dll
  - path: UAUtil\bin\Release\UAUtil.{version}.nupkg
    name: UAUtil.{version}.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: F08+ODn3ExAxMZuWu9p7b1pGQYfycvQi8RqYUgU6zWy841j3DQDgosDfaE4iyyvO