platform: Any CPU

os: Visual Studio 2017

configuration:
- Release

before_build:
- dotnet restore

build:
  project: UAUtil.sln

test_script:
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full UAUtil.Test\UAUtil.Test.csproj" -filter:"+[UAUtil*]* -[UAUtil.Test*]*" -output:".\coverage.xml"
  - codecov -f .\coverage.xml -t %CODECOV_TOKEN%